<h2>Library Importing</h2>

In [1]:
import numpy as np
import pandas as pd

<h2>DataSet Import</h2>

In [2]:
#importing dataset
app_df=pd.read_csv('Play Store Data.csv')
rev_df=pd.read_csv('User Reviews.csv')
print('App dataset Shape: ',app_df.shape)
print('Review dataset Shape: ',rev_df.shape)

App dataset Shape:  (10841, 13)
Review dataset Shape:  (64295, 5)

<h3>Dataset and Info</h3>

<h4>Application Dataset</h4>

In [3]:
app_df.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,"""i DT"" Fútbol. Todos Somos Técnicos.",SPORTS,NaN,27,3.6M,500+,Free,0,Everyone,Sports,"October 7, 2017",0.22,4.1 and up
1,.R,TOOLS,4.5,259,203k,"10,000+",Free,0,Everyone,Tools,"September 16, 2014",1.1.06,1.5 and up
2,/u/app,COMMUNICATION,4.7,573,53M,"10,000+",Free,0,Mature 17+,Communication,"July 3, 2018",4.2.4,4.1 and up

In [4]:
app_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.1+ MB

In [5]:
#Shape
print('Shape:',app_df.shape)

#Count of nan values
app_df.isna().sum()

Shape: (10841, 13)

App                  0
Category             1
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               1
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

<h4>Review Dataset</h4>

In [6]:
rev_df.head(3)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN

In [7]:
rev_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     64295 non-null  object
 1   Translated_Review       37427 non-null  object
 2   Sentiment               37432 non-null  object
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.5+ MB

In [8]:
#Shape
print('Shape:',rev_df.shape)

#Count of nan values
rev_df.isna().sum()

Shape: (64295, 5)

App                           0
Translated_Review         26868
Sentiment                 26863
Sentiment_Polarity        26863
Sentiment_Subjectivity    26863
dtype: int64

<h2>Data Cleaning</h2>

<h4>Application</h4>

In [9]:
#drop a row iff all the columns are empty
app_df.drop_duplicates(inplace=True)

#rows will be dropped having na value in Rating Column(other columns(na or non-na) doesn't matter)
app_df=app_df.dropna(subset=['Rating'])

#rows will be dropped having na value in App Column
app_df.drop_duplicates(subset='App',inplace=True)

#filling na values with mode value of the respective column
for column in app_df.columns:
    app_df[column].fillna(app_df[column].mode()[0],inplace=True)

#rating more than 5 are removed
app_df=app_df[app_df['Rating']<=5]

C:\Users\Nikhil\AppData\Local\Temp\ipykernel_13528\3253160578.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_df[column].fillna(app_df[column].mode()[0],inplace=True)
C:\Users\Nikhil\AppData\Local\Temp\ipykernel_13528\3253160578.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_df[column].fillna(app_df[column].mode()[0],inplace=True)

<h4>Review</h4>

In [10]:
#Delete rows having na value in Translated_column
rev_df.dropna(subset='Translated_Review', inplace=True)

<h2>DataSet Transformation</h2>

In [11]:
app_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1,.R,TOOLS,4.5,259,203k,"10,000+",Free,0,Everyone,Tools,"September 16, 2014",1.1.06,1.5 and up
2,/u/app,COMMUNICATION,4.7,573,53M,"10,000+",Free,0,Mature 17+,Communication,"July 3, 2018",4.2.4,4.1 and up
3,[adult swim],FAMILY,3.6,21433,21M,"1,000,000+",Free,0,Mature 17+,Entertainment,"May 29, 2018",3.0.1805181047,5.0 and up
4,[BN] Blitz,SPORTS,3.2,4,5.6M,100+,Free,0,Everyone,Sports,"May 17, 2018",4.6,4.3 and up
6,[root] Pry-Fi,TOOLS,3.9,6736,72k,"500,000+",Free,0,Everyone,Tools,"February 2, 2014",1.2,4.2 and up

In [12]:
rev_df.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000
5,10 Best Foods for You,Best way,Positive,1.00,0.300000

In [13]:
app_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8197 entries, 1 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8197 non-null   object
 1   Category        8197 non-null   object
 2   Rating          8197 non-null   float64
 3   Reviews         8197 non-null   int64
 4   Size            8197 non-null   object
 5   Installs        8197 non-null   object
 6   Type            8197 non-null   object
 7   Price           8197 non-null   object
 8   Content Rating  8197 non-null   object
 9   Genres          8197 non-null   object
 10  Last Updated    8197 non-null   object
 11  Current Ver     8197 non-null   object
 12  Android Ver     8197 non-null   object
dtypes: float64(1), int64(1), object(11)
memory usage: 896.5+ KB

In [14]:
#simple type conversion
app_df['Installs']=app_df['Installs'].str.replace('+','').str.replace(',','').astype(int)
app_df['Price']=app_df['Price'].str.replace('$','').astype(float)

#M and k removed and type conversion of Size
for i in app_df.index:
    app_df.at[i,'size']=app_df.at[i,'Size'][-1]
app_df['Size']=app_df['Size'].str.replace('M','').str.replace('k','').str.replace('Varies with device','0').astype(float)

#instead of k and M converting in actual number
for i in app_df.index:
    if(app_df.at[i,'size']=='k'):
        app_df.at[i,'Size']=app_df.at[i,'Size']*(2**10)
    elif (app_df.at[i,'size']=='M'):
        app_df.at[i,'Size']=app_df.at[i,'Size']*(2**20)
app_df.drop(columns=['size'],inplace=True)
app_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1,.R,TOOLS,4.5,259,207872.0,10000,Free,0.0,Everyone,Tools,"September 16, 2014",1.1.06,1.5 and up
2,/u/app,COMMUNICATION,4.7,573,55574528.0,10000,Free,0.0,Mature 17+,Communication,"July 3, 2018",4.2.4,4.1 and up
3,[adult swim],FAMILY,3.6,21433,22020096.0,1000000,Free,0.0,Mature 17+,Entertainment,"May 29, 2018",3.0.1805181047,5.0 and up
4,[BN] Blitz,SPORTS,3.2,4,5872025.6,100,Free,0.0,Everyone,Sports,"May 17, 2018",4.6,4.3 and up
6,[root] Pry-Fi,TOOLS,3.9,6736,73728.0,500000,Free,0.0,Everyone,Tools,"February 2, 2014",1.2,4.2 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,ZUL - Rotativo Digital BH,AUTO_AND_VEHICLES,4.2,29,0.0,10000,Free,0.0,Everyone,Auto & Vehicles,"August 1, 2018",1.6.5,4.1 and up
10837,zulily - Shop Daily Deals in Fashion and Home,SHOPPING,4.5,28560,0.0,1000000,Free,0.0,Everyone,Shopping,"July 23, 2018",Varies with device,Varies with device
10838,Zumper - Apartment Rental Finder,HOUSE_AND_HOME,4.4,11200,26214400.0,1000000,Free,0.0,Everyone,House & Home,"July 16, 2018",4.5.15,5.0 and up
10839,Zynga Poker – Texas Holdem,GAME,4.4,1986068,54525952.0,50000000,Free,0.0,Teen,Casino,"July 25, 2018",21.54,4.1 and up
10840,#NAME?,COMICS,3.5,115,9542041.6,10000,Free,0.0,Mature 17+,Comics,"July 13, 2018",5.0.12,5.0 and up

In [15]:
#Categorization of Rating
def review_rating(rating):
    if rating >=4:
        return 'top rated app'
    elif rating >= 3:
        return 'above average'
    elif rating >=2:
        return 'Average'
    else:
        return 'below average'
app_df['Rating_Group']=app_df['Rating'].apply(review_rating)

#Calculating revenue for each app
app_df['Revenue']=app_df['Installs']*app_df['Price'].astype(float)
app_df.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Rating_Group,Revenue
1,.R,TOOLS,4.5,259,207872.0,10000,Free,0.0,Everyone,Tools,"September 16, 2014",1.1.06,1.5 and up,top rated app,0.0
2,/u/app,COMMUNICATION,4.7,573,55574528.0,10000,Free,0.0,Mature 17+,Communication,"July 3, 2018",4.2.4,4.1 and up,top rated app,0.0
3,[adult swim],FAMILY,3.6,21433,22020096.0,1000000,Free,0.0,Mature 17+,Entertainment,"May 29, 2018",3.0.1805181047,5.0 and up,above average,0.0

<h3>Both Data Merged</h3>

In [16]:
df=pd.merge(app_df,rev_df,on='App', how='inner')
df.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Rating_Group,Revenue,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,HEALTH_AND_FITNESS,4.0,2490,3984588.8,500000,Free,0.0,Everyone 10+,Health & Fitness,"February 17, 2017",1.9,2.3.3 and up,top rated app,0.0,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,HEALTH_AND_FITNESS,4.0,2490,3984588.8,500000,Free,0.0,Everyone 10+,Health & Fitness,"February 17, 2017",1.9,2.3.3 and up,top rated app,0.0,This help eating healthy exercise regular basis,Positive,0.25,0.288462